### ISSUE TITLE
Error building

### ISSUE THREAD

**Issue by carloslopezcastro** [mkay1375/BackupGram#1]
Hello, congratulations for the work you have done, I am trying to build the code but I get the following errors, could you tell me what it is.

[WARNING] 
[WARNING] Some problems were encountered while building the effective model for ir.mkay:BackupGram:jar:0.9.6
[WARNING] 'build.plugins.plugin.version' for org.apache.maven.plugins:maven-compiler-plugin is missing. @ line 100, column 15
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] 
[INFO] -------------------------< ir.mkay:BackupGram >-------------------------
[INFO] Building BackupGram 0.9.6
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ BackupGram ---
[INFO] Deleting /Users/username/BackupGram/target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ BackupGram ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 15 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ BackupGram ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1099 source files to /Users/username/BackupGram/target/classes
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.947 s
[INFO] Finished at: 2022-01-28T20:21:05+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project BackupGram: Fatal error compiling: java.lang.ExceptionInInitializerError: Unable to make field private com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors com.sun.tools.javac.processing.JavacProcessingEnvironment.discoveredProcs accessible: module jdk.compiler does not "opens com.sun.tools.javac.processing" to unnamed module @54609a9 -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by mkay1375** [comment]
Hi, thanks!

I've just built it with Java 8 (from Oracle; with OpenJDK maven couldn't download files!) without any problem; It seems you're using a newer version of Java; try with Oracle's Java 8 and let me know if the problem still exists.

**Comment by carloslopezcastro** [comment]
hello again I have installed oracle java 8: 

java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) 64-Bit Server VM (build 25.0-b70, mixed mode)

 and it gives me this error:

[INFO] Compiling 1099 source files to /home/user/Desktop/BackupGram/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/user/Desktop/BackupGram/src/main/java/ir/mkay/javafx/util/FxUtils.java:[9,28] cannot find symbol
  symbol:   class Alert
  location: package javafx.scene.control
[ERROR] /home/user/Desktop/BackupGram/src/main/java/ir/mkay/javafx/util/FxUtils.java:[10,28] cannot find symbol
  symbol:   class ButtonBar
  location: package javafx.scene.control
[ERROR] /home/user/Desktop/BackupGram/src/main/java/ir/mkay/javafx/util/FxUtils.java:[11,28] cannot find symbol
  symbol:   class ButtonType
  location: package javafx.scene.control
[ERROR] /home/user/Desktop/BackupGram/src/main/java/ir/mkay/javafx/util/FxUtils.java:[86,39] package Alert does not exist
[ERROR] /home/user/Desktop/BackupGram/src/main/java/ir/mkay/javafx/util/FxUtils.java:[96,28] cannot find symbol
  symbol:   class ButtonType
  location: class ir.mkay.javafx.util.FxUtils
[INFO] 5 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.048 s
[INFO] Finished at: 2022-01-29T07:28:09-08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project BackupGram: Compilation failure: Compilation failure: 
[ERROR] /home/user/Desktop/BackupGram/src/main/java/ir/mkay/javafx/util/FxUtils.java:[9,28] cannot find symbol
[ERROR]   symbol:   class Alert
[ERROR]   location: package javafx.scene.control
[ERROR] /home/user/Desktop/BackupGram/src/main/java/ir/mkay/javafx/util/FxUtils.java:[10,28] cannot find symbol
[ERROR]   symbol:   class ButtonBar
[ERROR]   location: package javafx.scene.control
[ERROR] /home/user/Desktop/BackupGram/src/main/java/ir/mkay/javafx/util/FxUtils.java:[11,28] cannot find symbol
[ERROR]   symbol:   class ButtonType
[ERROR]   location: package javafx.scene.control
[ERROR] /home/user/Desktop/BackupGram/src/main/java/ir/mkay/javafx/util/FxUtils.java:[86,39] package Alert does not exist
[ERROR] /home/user/Desktop/BackupGram/src/main/java/ir/mkay/javafx/util/FxUtils.java:[96,28] cannot find symbol
[ERROR]   symbol:   class ButtonType
[ERROR]   location: class ir.mkay.javafx.util.FxUtils
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

**Comment by mkay1375** [comment]
I think you need a newer version of Java 8 (I was using JDK 8u152); however as it's become a little awkward, in the next few days, I'll upgrade the project to support newer versions of Java and these problems will hopefully be gone.

**Comment by carloslopezcastro** [comment]
Hello again,
I have compiled using the **JDK 8u152 version**, and it has worked perfectly, again congratulations for the work and thank you very much

**Comment by mkay1375** [comment]
Thank you!
