### ISSUE TITLE
Authorisation Error

### ISSUE THREAD

**Issue by Kartoz** [mkay1375/BackupGram#2]
Greetings! I am very interested in your work. Having such a program would help me a lot. But I am unable to use it. I compiled the file according to your instructions, got the telegram api and hash, the program started. But when I try to login I get an error.

2022-04-16 09:42:10 [main] INFO  ir.mkay.backupgram.Main - App started
╨░╨┐╤А 16, 2022 9:42:17 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELMAIN] --------------KERNEL CREATED--------------
╨░╨┐╤А 16, 2022 9:42:17 AM org.telegram.bot.services.BotLogger warning
WARNING: [KernelPersistence] Loaded state in 1 ms
╨░╨┐╤А 16, 2022 9:42:17 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELMAIN] org.telegram.bot.kernel.KernelComm init in 12 ms
╨░╨┐╤А 16, 2022 9:42:17 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELMAIN] org.telegram.bot.kernel.KernelAuth init in 3 ms
╨░╨┐╤А 16, 2022 9:42:17 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] #1: Creating key
╨░╨┐╤А 16, 2022 9:42:17 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELMAIN] org.telegram.bot.kernel.KernelComm init in 152 ms
╨░╨┐╤А 16, 2022 9:42:20 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] mtproto#1001: onSessionCreated
╨░╨┐╤А 16, 2022 9:42:20 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] mtproto#1001: onSessionCreated
╨░╨┐╤А 16, 2022 9:42:20 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] mtproto#1002: onSessionCreated
╨░╨┐╤А 16, 2022 9:42:20 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELAUTH] Loaded DC list
╨░╨┐╤А 16, 2022 9:42:20 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELAUTH] Sending code to phone +380964445566...
╨░╨┐╤А 16, 2022 9:42:20 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] auth.sendCode#86aef0ec
╨░╨┐╤А 16, 2022 9:42:20 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] #2: Creating key
╨░╨┐╤А 16, 2022 9:42:21 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] mtproto#1003: onSessionCreated
╨░╨┐╤А 16, 2022 9:42:21 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] mtproto#1004: onSessionCreated
╨░╨┐╤А 16, 2022 9:42:21 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] mtproto#1003: onSessionCreated
╨░╨┐╤А 16, 2022 9:42:21 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELAUTH] sent Code
╨░╨┐╤А 16, 2022 9:42:21 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELMAIN] org.telegram.bot.kernel.KernelAuth started in 4432 ms
╨░╨┐╤А 16, 2022 9:42:21 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELMAIN] org.telegram.bot.kernel.MainHandler init in 6 ms
╨░╨┐╤А 16, 2022 9:42:21 AM org.telegram.bot.services.BotLogger info
INFO: [KERNELMAIN] ----------------BOT READY-----------------
╨░╨┐╤А 16, 2022 9:42:32 AM org.telegram.bot.services.BotLogger warning
WARNING: [TELEGRAMAPI] auth.signIn#bcd51581
[1642022.log](https://github.com/mkay1375/BackupGram/files/8499413/1642022.log)

I would be very grateful if you could help me figure it out.

**Comment by mkay1375** [comment]
Hi, I'm glad this project is useful to you.

I think you have enabled password authentication in your account and unfortunately BackupGram doesn't support it.

Please remove password authentication from your account and see if the problem still exists.

**Comment by Kartoz** [comment]
If you mean the 2FA password, then it is disabled, I used a newly registered account. Only sms

**Comment by mkay1375** [comment]
Yes, I meant two-step verification.

I've just tested the app with java 1.8.0_231 on windows and it worked.

In the log file you provided there's a `{SEVERE} TELEGRAMAPI - java.util.concurrent.ExecutionException: org.telegram.api.engine.RpcException: SESSION_PASSWORD_NEEDED` line which most probably means 2FA is enabled.

As you're using a fresh account, then I don't know what's problem.
